/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import utils.SignatureRequestUserModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.SignatureRequestUserDto;
import models.UserDto;
import services.impl.ApiService;

/**
 *
 * @author USUARIO
 */
public final class SignatureRequestUser extends javax.swing.JPanel {

    private final UserDto userCurrent;
    List<SignatureRequestUserDto> listRequestUser = new ArrayList<>();
    List<SignatureRequestUserDto> listRequestUserFilter;
    SignatureRequestUserDto requestUser;
    ApiService apiService = new ApiService();
    int[][] dimensions = null;

    /**
     * Creates new form SignatureRequestUser
     *
     * @param userCurrent
     */
    public SignatureRequestUser(UserDto userCurrent) {
        this.userCurrent = userCurrent;
        initComponents();
        this.table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = table.rowAtPoint(e.getPoint());

                requestUser = listRequestUserFilter.get(row);
                showRequestUser();
            }
        });
        this.comboFilter.setSelectedIndex(0);
        searchData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnDownload = new javax.swing.JButton();
        btnSing = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPosX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPosY = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboFilter = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNumPage = new javax.swing.JTextField();
        lblMaxAxisY = new javax.swing.JLabel();
        lblMaxAxisX = new javax.swing.JLabel();
        lblMaxPage = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        btnDownload.setText("Download");
        btnDownload.setEnabled(false);
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnSing.setText("Sing");
        btnSing.setEnabled(false);
        btnSing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Document Signature Form");

        jLabel2.setText("x-axis position");

        txtPosX.setText("0");

        jLabel3.setText("y-axis position");

        txtPosY.setText("0");

        txtId.setEditable(false);

        jLabel4.setText("Type Request");

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Signed" }));
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });

        jLabel5.setText("Num page");

        txtNumPage.setText("1");
        txtNumPage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumPageFocusLost(evt);
            }
        });

        lblMaxAxisY.setText("Max: 0");

        lblMaxAxisX.setText("Max: 0");

        lblMaxPage.setText("Max: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumPage)
                            .addComponent(txtPosX)
                            .addComponent(txtId)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaxAxisY))
                            .addComponent(txtPosY)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaxPage))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnSing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownload)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaxAxisX)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblMaxPage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblMaxAxisY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPosY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaxAxisX)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPosX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSing)
                            .addComponent(btnDownload))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        showTable();
    }//GEN-LAST:event_comboFilterActionPerformed

    private void btnSingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingActionPerformed

        try {
            if (!txtPosX.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "non-numeric x-axis", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!txtPosY.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "non-numeric y-axis", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!txtNumPage.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "non-numeric page number", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int posx = Integer.parseInt(txtPosX.getText());
            int posy = Integer.parseInt(txtPosY.getText());
            int numPage = Integer.parseInt(txtNumPage.getText());
            
            if (numPage > this.dimensions.length) {
                JOptionPane.showMessageDialog(this, "Page number greater than maximum", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (numPage <= 0) {
                JOptionPane.showMessageDialog(this, "Page number invalid", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (posx > this.dimensions[numPage-1][0]) {
                JOptionPane.showMessageDialog(this, "X-axis greater than maximum", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (posy > this.dimensions[numPage-1][1]) {
                JOptionPane.showMessageDialog(this, "Y-axis greater than maximum", "Form Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            requestUser.setPos_x(posx);
            requestUser.setPos_y(posy);
            requestUser.setNum_page(numPage);
            
            requestUser.setSigned(true);

            apiService.getSignatureRequestUser().updateRequest(requestUser);
            JOptionPane.showMessageDialog(this, "Singed Request", "OK", JOptionPane.INFORMATION_MESSAGE);
            searchData();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Form Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSingActionPerformed

    private void txtNumPageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumPageFocusLost
        int numPage = 0;
        if (txtNumPage.getText().matches("\\d+")) {
            numPage = Integer.parseInt(this.txtNumPage.getText());
        }
        if (dimensions != null && numPage > 0 && numPage <= dimensions.length) {
            lblMaxAxisX.setText("Max:" + dimensions[numPage-1][0]);
            lblMaxAxisY.setText("Max:" + dimensions[numPage-1][1]);
        } else {
            lblMaxAxisX.setText("Max:-");
            lblMaxAxisY.setText("Max:-");            
        }
    }//GEN-LAST:event_txtNumPageFocusLost

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select Folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        chooser.setAcceptAllFileFilterUsed(false);
        //
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION && this.requestUser != null) {
            try {
                String dir = chooser.getSelectedFile().toString();
                apiService.getFileService().downloadFileSigned(dir, this.requestUser.getRequest());
            } catch (Exception ex) {                
            }
        }  
    }//GEN-LAST:event_btnDownloadActionPerformed

    void searchData() {
        try {
            listRequestUser = apiService.getSignatureRequestUser().getRequestUser(userCurrent.getId());
            showTable();
        } catch (Exception ex) {
        }
    }

    void showTable() {
        try {
            listRequestUserFilter = new ArrayList<>();
            for (SignatureRequestUserDto d : listRequestUser) {
                if ((!d.isSigned() && this.comboFilter.getSelectedIndex() == 0)
                        || (d.isSigned() && this.comboFilter.getSelectedIndex() == 1)) {
                    listRequestUserFilter.add(d);
                }
            }
            table.setModel(new SignatureRequestUserModel(listRequestUserFilter));
            requestUser = null;

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    void showRequestUser() {
        this.btnDownload.setEnabled(true);
        this.btnSing.setEnabled(true);
        txtId.setText(this.requestUser.getId() + "");
        txtPosX.setText(this.requestUser.getPos_x() + "");
        txtPosY.setText(this.requestUser.getPos_y() + "");
        int numPage = this.requestUser.getNum_page() != 0 ? this.requestUser.getNum_page() : 1;
        txtNumPage.setText(numPage + "");
        this.dimensions = this.requestUser.getRequestDto().getDocumentDto().getDimensionsPdf();
        if (dimensions != null && numPage > 0 && numPage <= dimensions.length) {
            lblMaxPage.setText("Max:" + dimensions.length);
            lblMaxAxisX.setText("Max:" + dimensions[numPage-1][0]);
            lblMaxAxisY.setText("Max:" + dimensions[numPage-1][1]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSing;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaxAxisX;
    private javax.swing.JLabel lblMaxAxisY;
    private javax.swing.JLabel lblMaxPage;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumPage;
    private javax.swing.JTextField txtPosX;
    private javax.swing.JTextField txtPosY;
    // End of variables declaration//GEN-END:variables
}
